# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        my_thumb_medium:
            filters:
                thumbnail:
                    size: [400,300]
                    mode: outbound
                    allow_upscale: true

        my_thumb_small:
            filters:
                thumbnail:
                    size: [200,200]
                    mode: outbound
                    allow_upscale: true
        
